development:
  adapter: postgresql
  encoding: unicode
  database: crossword_development
  pool: 5
  host: localhost
  # username: ubuntu
  # password: ubuntu


test:
  adapter: postgresql
  encoding: unicode
  database: crossword_test
  pool: 5
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: crossword_production
  pool: 5
  host: localhost

